### ISSUE TITLE
nice tool and  new feature request

### ISSUE THREAD

**Issue by ygwangmsra** [danielscherzer/GLSL#51] opened 2020-03-31 04:38 UTC
Can you add a new feature to support raw string literals? such as

R"(
#version 400

layout (location = 0) in vec3 pos;
void main()
{
...
}
)"

and this file can be also saved as xxx.vert for highlight

**Comment by danielscherzer** [comment] 2020-03-31 06:15
Hi,
do you suggest something like in this closed issue #35 ? Or do you want the syntax highlighting to appear inside a cpp file?

**Comment by ygwangmsra** [comment] 2020-04-07 03:51
Thanks a lot! I want a compile time string generation. So maybe the best way is to comment the R"( ) for debugging and uncomment it for deploying.

I will close this issue.

**Comment by lestat1983** [comment] 2021-02-25 17:40
> If you put the R"( at the beginning of a shader the compiler will show this as an error, but syntax highlighting will still work. The downside is that other errors in the code are no longer detected.
Since the last update (version 10) this isn't true.. 
Here a screenshot:
![image](https://user-images.githubusercontent.com/32831799/109193629-dd82c000-7798-11eb-8e20-557e8038d1c0.png)

Is there any workaround/settings to re-enable the syntax highline?

**Comment by danielscherzer** [comment] 2021-03-03 10:12
Because the old syntax coloring did not handle strings (for instance for include statements) I added handling of strings.
To allow your use of string literals I now stop string parsing at line ends, which makes sense anyway.

**Comment by danielscherzer** [comment] 2021-04-27 17:36
can we close this issue?

**Comment by lestat1983** [comment] 2021-04-28 15:32
yep, the issue is solved in 0.10.125

Il giorno mar 27 apr 2021 alle ore 19:36 Daniel Scherzer <
***@***.***> ha scritto:

**Closed** 2021-04-28 18:37 UTC
