### ISSUE TITLE
Extension doens't work with any but .glsl files if "Syntax Highlighting Pack" extension is installed

### ISSUE THREAD

**Issue by spiralsam** [danielscherzer/GLSL#69] opened 2020-08-07 12:56 UTC
I disabled Syntax Highlighting Pack as a hunch to discover what seems like a conflict here. When this extension is installed
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.SyntaxHighlightingPack

I could only get .glsl files to work. Otherwise .vert files try to be parsed (it looks as like maybe C++ for my C++ project, causing C++-style errors, and syntax highlighting not working properly). If I changed .vert in to .vert1 in "GLSL language integration" -> Configuration -> "Vertex shader type file extensions while this other extension is installed, then I rename my .vert files to .vert1, then things seem to work like intended. Same for .frag. These are the only two extensions I tried.

**Comment by danielscherzer** [comment] 2020-08-17 11:32
Thanks for your feedback! I can confirm this behaviour. 
I asked Mads Kristensen how to resolve this problem.

**Comment by danielscherzer** [comment] 2020-09-27 06:54
Duplicate of #32. This has the same underlying problem. So I close this issue and leave Issue #32 open

**Closed by danielscherzer** 2020-09-27 06:54 UTC
