### ISSUE TITLE
Does not work with VS 2022

### ISSUE THREAD

**Issue by ComeOnAndSam** [danielscherzer/GLSL#101] opened 2022-04-18 14:42 UTC
### Installed product versions
- Visual Studio: Community 2022
- This extension: 0.11.158

### Description
Replace this text with a short description

### Steps to recreate
1. Install the 2022 version of the extension
2. Launch VS 2022
3. Error message pops up
4. "The 'Microsoft.VisualStudio.Editor.Implementation.EditorPackage' package did no load correctly"

### Current behavior
VS 2022 breaks entirely and can't compile anything after installing this extension

Activity log pointed at by the error message: 
[ActivityLog.zip](https://github.com/danielscherzer/GLSL/files/8506308/ActivityLog.zip)

**Comment by c-mendoza** [comment] 2022-05-03 15:17
Same issue here.

**Comment by alexfevery** [comment] 2022-06-10 22:33
I also cannot get it to work for VS2022.  None of the file extension types work. Version 17.2.0

**Comment by danielscherzer** [comment] 2022-06-11 17:00
Does any of you use nsight?

**Comment by alexfevery** [comment] 2022-06-11 17:28
> Does any of you use nsight?

No. nor any other tools for graphics programming.

**Comment by alexfevery** [comment] 2022-06-11 17:47
I have figured out why it wasn't working in my case.   Under Tools>Options>Text Editor>File Extension  I had added glsl file types with the "Microsoft Visual C#" editing experience.  Removing this makes your extension work again.  But now I lost the ability to use "Format Document".  Any way to fix this?

**Comment by MarkusMiller** [comment] 2022-07-25 21:59
I have the same issues with the community edition of VS 2022. I do use NSsight, though, but it seems the issue occurs independently from that. When I enable the extension, the entire editor is busted and doesn't show anything anymore.

**Comment by danielscherzer** [comment] 2022-07-28 19:14
> Removing this makes your extension work again. But now I lost the ability to use "Format Document". Any way to fix this?
I think for this to work again I would have to implement this functionality for glsl files anew. If anyone has a shortcut for this please feel free to reply.

**Comment by kyamant** [comment] 2022-08-01 19:01
On VS 2022 Enterprise (Version 17.2.6), I am getting "_Could not create glslRayGeneration instance. Are your drivers up-to-date?_" message.
Moreover, this is causing devenv.exe to disable my screen timeout!
```
$powercfg -requests
DISPLAY:
[PROCESS] \Device\HarddiskVolume7\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe
```

**Comment by danielscherzer** [comment] 2022-08-03 10:35
> On VS 2022 Enterprise (Version 17.2.6), I am getting "_Could not create glslRayGeneration instance. Are your drivers up-to-date?_" message. Moreover, this is causing devenv.exe to disable my screen timeout!
> 
> ```
> $powercfg -requests
> DISPLAY:
> [PROCESS] \Device\HarddiskVolume7\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe
> ```

If you get this error the extension could be loaded. So this is a different issue....
But this should indicate that you try to write a ray generation shader, but your graphics card driver does not support this. You can either use an [external compiler ](https://github.com/danielscherzer/GLSL#external-compiler) or switch of error squiggle generation in the options.

**Comment by kyamant** [comment] 2022-08-03 10:58
my graphics card is a RTX 3070 ti and driver is the latest from nvidia 516.59!
The only solution I see is to disable/uninstall your extension

**Comment by MarkusMiller** [comment] 2022-08-03 14:39
Hello, I also tried your latest release (the one 7 days ago) and it's still the same error. The editor is reporting this error:
`System.ArgumentException: No EditorOptionDefinition export found for the given option name: EditingState/EditingStateEndingMargin
Parametername: optionId`

And there were a couple of error messages before, pointing to the ActivityLog for further information
[ActivityLog.xml.txt](https://github.com/danielscherzer/GLSL/files/9252419/ActivityLog.xml.txt)
.

**Comment by kyamant** [comment] 2022-08-03 15:16
Setting the external compiler to `%VULKAN_SDK%\Bin\glslangValidator.exe` and arguments to `--target-env spirv1.4` got rid of the message.
The screen timeout is still disabled until I close that VS2022 instance:
```
$powercfg -requests
DISPLAY:
[PROCESS] \Device\HarddiskVolume7\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe
```

**Comment by danielscherzer** [comment] 2022-08-03 18:21
> Hello, I also tried your latest release (the one 7 days ago) and it's still the same error. The editor is reporting this error: `System.ArgumentException: No EditorOptionDefinition export found for the given option name: EditingState/EditingStateEndingMargin Parametername: optionId`
> 
> And there were a couple of error messages before, pointing to the ActivityLog for further information [ActivityLog.xml.txt](https://github.com/danielscherzer/GLSL/files/9252419/ActivityLog.xml.txt) .

This error could be related with a corrupt ComponentModelCache of Visual Studio as discussed here:
https://stackoverflow.com/questions/33168357/no-editoroptiondefinition-export-found-for-the-given-option-nametextviewhost-l

**Comment by TheSabby101** [comment] 2022-08-08 03:03
The highlighting stopped working the moment I installed nsight, I don't see any errors though.

**Comment by danielscherzer** [comment] 2022-08-08 10:27
This is a known issue #103 and #76 with nsight. one possible workaround is to use different shader filename extensions

**Comment by MarkusMiller** [comment] 2022-08-08 15:05
> > Hello, I also tried your latest release (the one 7 days ago) and it's still the same error. The editor is reporting this error: `System.ArgumentException: No EditorOptionDefinition export found for the given option name: EditingState/EditingStateEndingMargin Parametername: optionId`
> > And there were a couple of error messages before, pointing to the ActivityLog for further information [ActivityLog.xml.txt](https://github.com/danielscherzer/GLSL/files/9252419/ActivityLog.xml.txt) .
> 
> This error could be related with a corrupt ComponentModelCache of Visual Studio as discussed here: https://stackoverflow.com/questions/33168357/no-editoroptiondefinition-export-found-for-the-given-option-nametextviewhost-l

I tried the suggested solution there, but unfortunately, it didn't change anything. It's still the same popup error when opening a solution, telling me, that either a recent change in configuration or installation of an extension might have caused the problem. Then I have to disable the GLSL language integration extension and all is back to working again.

**Comment by danielscherzer** [comment] 2022-08-09 13:38
> I tried the suggested solution there, but unfortunately, it didn't change anything. It's still the same popup error when opening a solution, telling me, that either a recent change in configuration or installation of an extension might have caused the problem. Then I have to disable the GLSL language integration extension and all is back to working again.
> 
> Edit: Turns out, though, that after updating Visual Studio (it somehow just became available today) it now works without issues.

Thanks for the feedback. Visual Studio 2022 seems to cause on/off problems, but I do not know what the root issue is.

**Comment by alexfevery** [comment] 2022-08-09 15:11
The extension is working well for me but its really a pain having to format and tab align the code manually. Is it possible to add GLSL as an option here? That way we can set it up to autoformat the document to our liking. 

<img width="513" alt="image" src="https://user-images.githubusercontent.com/25232648/183687635-a1593a93-1ff4-40b1-8863-0e4ccb9abab2.png">

**Comment by MarkusMiller** [comment] 2022-08-09 15:41
> The extension is working well for me but its really a pain having to format and tab align the code manually. Is it possible to add GLSL as an option here? That way we can set it up to autoformat the document to our liking.
> 
> <img alt="image" width="513" src="https://user-images.githubusercontent.com/25232648/183687635-a1593a93-1ff4-40b1-8863-0e4ccb9abab2.png">

Actually, auto-formatting works, if I rename my shader extension back to *.glsl (NSIght is probably taking over then again, I assume)... doesn't work, though, when the file extension is *.frag/*.vert...

**Comment by danielscherzer** [comment] 2022-08-16 07:19
For issues with nvidia nsight please post to issue #76
For new features, like auto format please open a new thread.
For this thread the issue is VS 2022. Does it still not work for somebody after upgrading to VS 17.3?

**Comment by danielscherzer** [comment] 2022-08-16 07:20
> > The extension is working well for me but its really a pain having to format and tab align the code manually. Is it possible to add GLSL as an option here? That way we can set it up to autoformat the document to our liking.
> > <img alt="image" width="513" src="https://user-images.githubusercontent.com/25232648/183687635-a1593a93-1ff4-40b1-8863-0e4ccb9abab2.png">
> 
> Actually, auto-formatting works, if I rename my shader extension back to *.glsl (NSIght is probably taking over then again, I assume)... doesn't work, though, when the file extension is _.frag/_.vert...

Yes I would guess that too.

**Comment by alexfevery** [comment] 2022-08-16 14:43
Can you explain how to do that? I really would like auto formatting. For mine adding its extension to VS options to enable auto formatting will disable error glsl highlighting. Here I added .frag but not .vert and only .vert error highlighting works.  (I have no nsight installed)
<img width="906" alt="image" src="https://user-images.githubusercontent.com/25232648/184908079-f3fedea2-9ea9-4b76-9f3b-ce7a9e6ac7e5.png">

**Comment by danielscherzer** [comment] 2022-08-17 06:43
This would be a new feature. A new issue #105 is now open for this.

**Comment by danielscherzer** [comment] 2022-08-17 07:02
Any startup/initialization problems with VS 17.3 and the extension? Otherwise I would close this issue.

**Closed** 2023-06-17 08:13 UTC
