### ISSUE TITLE
 Isn't working on .glsl files

### ISSUE THREAD

**Issue by lalishansh** [danielscherzer/GLSL#103] opened 2022-05-13 02:50 UTC
### Installed product versions
- Visual Studio: [2022 Community]
- This extension: [example 0.11.159]

### Description
cannot register file extension (.glsl)
![image](https://user-images.githubusercontent.com/61790879/168201436-c377af0f-4e85-4b22-92be-9c001009dd45.png)

### Steps to recreate
Unknown, using Jetbrains ReSharper along side

### Current behavior
Isn't working on .glsl files

### Expected behavior
should work on .glsl files

**Comment by danielscherzer** [comment] 2022-05-16 07:23
Possible duplicate of #76. Please check the steps described there.

**Comment by ishanshLal-tRED** [comment] 2022-05-16 16:28
I have cuda and Night installed, could that be creating problem

**Comment by danielscherzer** [comment] 2022-05-16 19:21
Yes, nsight seems to take posession of the usual file extensions for shaders. I found no wayy to overrule nsight, appart from setting different file extensions in the options of my extension.

**Comment by danielscherzer** [comment] 2022-08-16 07:17
I will close this issue because issue #76 is discussing this problem in more detail.

**Closed by danielscherzer** 2022-08-16 07:17 UTC
