### ISSUE TITLE
Support for .glsl.h files

### ISSUE THREAD

**Issue by RikoOphorst** [danielscherzer/GLSL#66] opened 2020-07-08 09:17 UTC
Hello! 

In most of our projects we use `<filenamehere>.glsl.h` as the file extension, however while your extension works great on all other types of files, it doesn't seem to work for .glsl.h files.

I suspect that's due to Visual Studio treating ".h" files immediately as C++ header files. I've tried to look in the settings for Visual Studio itself so that files named ".glsl.h" don't get treated as C++ header files, but as it turns out Visual Studio only looks at whatever string of characters is after the last dot in the file name (which makes sense of course).

I was wondering whether there would be a way inside of this extension to overrule Visual Studio's file extension thingy, but specifically only for `.glsl.h` files.

If that is already possible within the extension, great! I'd like to know how!
If that isn't yet possible with the extension, do you think this is something that is could be added to it?

Thanks a lot!

**Comment by danielscherzer** [comment] 2020-07-09 17:48
You are right in assuming Visual Studio takes control over *.h files. Even for other extensions (see Issue #32) Visual Studio takes over and I do not know how to circumvent this. 
I use the `IFileExtensionRegistryService fileExtensionRegistry` to register "my" file extensions. For *.glsl.h" I do not get any error, but still VS is handling those files. For other of the special extensions, like vsh, I at least get an error. 
If you happen to chance on a way, I'm happy to include this in the extension.

Sorry!

**Comment by danielscherzer** [comment] 2020-09-27 06:52
Duplicate of #32

**Closed** 2020-09-27 06:53 UTC
